#默认钓王竞赛时长，单位秒
默认游戏时长: 600
灾难模式: true
#钓鱼钓到杂物的概率，
#假设写入10|100，那么概率就是10%，如果写10|1000，那就是千分之一
杂物概率: 10|100
灾难概率: 1|100
杂物模式: true
排名显示数量: 5
传送距离: 10
游戏世界:
  - world
  - game
玩家黑名单: [ ]
允许杂物上架: true
#灾难模式可能会遇到药水效果
#格式如下：
#药水效果|可能的最短持续效果-可能的最大持续效果
灾难模式药水效果:
  - 反胃|10-30
  - 中毒|20-60
鱼的附魔:
  - 精准采集
  - 击退
商店个性化介绍上限: 100
上架手续费: 10000
上架手续费货币: WC_Vault
上架转移排名: true
货币ID: WC_Vault
货币名称: 人头